name: Continuous Integeration

on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main
      - dev

jobs:
  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: ./
        run: npm install
      - name: Lint
        working-directory: ./
        run: npm run lint
      - name: Style check
        working-directory: ./
        run: npm run prettier-check
      - name: Build project
        working-directory: ./
        run: npm run build
